### PR TITLE
Prevent snapshot from incrementing version

### PR DESCRIPTION
**Pull request by CannonLock**
Closes: #1163

### CODE REVIEW

**Comment by CannonLock** [comment]
Easy fix, hopefully easy review. You can see the issue is resolved from the log snapshots of the docker builds before and after the change.

From the docker build action here:

```
#22 0.203     • git state                                      commit=8125e86ae6e306297b7df7019307591fbb2f6535 branch=HEAD current_tag=v0.0.0 previous_tag=<unknown> dirty=false
#22 0.203     • pipe skipped                                   reason=disabled during snapshot mode
#22 0.203   • parsing tag
#22 0.203   • setting defaults
#22 0.207   • snapshotting
#22 0.207     • building snapshot...                           version=0.0.0
```

From previous docker build actions:

```
#23 0.150     • git state                                      commit=b353acaa7b807243a6feffb9fa4480fa77f34031 branch=HEAD current_tag=v0.0.0 previous_tag=<unknown> dirty=false
#23 0.150     • pipe skipped                                   reason=disabled during snapshot mode
#23 0.151   • parsing tag
#23 0.151   • setting defaults
#23 0.154   • snapshotting
#23 0.154     • building snapshot...                           version=0.0.1-next
```

**Review by jhiemstrawisc — CHANGES_REQUESTED** [review]
Reassigned the review to myself since I was mucking with versioning/goreleaser in a sidequest.

Only comment is that it looks like `snapshot.name_template` is [deprecated](https://goreleaser.com/deprecations/#snapshotname_template). Can you update to `snapshot.version_template` as suggested by their docs?

**Comment by CannonLock** [comment]
@jhiemstrawisc We are using goreleaser/goreleaser:v1.21.0 in the container that I am fixing. Can we create a new ticket to upgrade that and address these deprecations and warnings there?

**Comment by jhiemstrawisc** [comment]
New ticket opened: https://github.com/PelicanPlatform/pelican/issues/1835

**Review by jhiemstrawisc — APPROVED** [review]

**Pull request merged**
