### PR TITLE
Remove Testing Code

### PR DESCRIPTION
**Pull request by CannonLock**
Added a 'cache' string [here](https://github.com/PelicanPlatform/pelican/pull/889/files#diff-e64181cce5ce490155a33cdffaa48b7eea8d1f07e4c7f0aef3ae447f720e7641) so that I could view the cache only `Lotman` configuration. 

This is to remove that leaked testing code.

### CODE REVIEW

**Review by haoming29 — APPROVED** [review]
LGTM!

**Comment by haoming29** [comment]
The parameter validation test failed due to no key exists for `Cache.Concurrency` which is an int type, not sure why this would cause error?

**Comment by CannonLock** [comment]
@haoming29 Looks like the `Cache.Concurrency` component list got dropped somewhere? I just tacked it on here as these are both minor changes.

**Comment by haoming29** [comment]
> @haoming29 Looks like the `Cache.Concurrency` component list got dropped somewhere? I just tacked it on here as these are both minor changes.

Thanks for the patch!

**Pull request merged**
