### PR TITLE
Uniform error handling

### PR DESCRIPTION
**Pull request by CannonLock**
- Add error helpers for api calls
- Create Uniform error handling and alerting interface
  - This is extensible to report many errors and complex errors to the user
- Moved all error handling to the new interface

Couple things that will make this a better path forward.

- Uniform interface makes error reporting the same on each page. 
  - Easier to implement for dev, easier to find for users.
  - Same function wraps all backend calls so we can do bulk handling of functionality. 
- Design allows for saving errors to pull up later ( Not yet implemented )
  - This will help if for some reason there is multiple errors in a row 

Closes https://github.com/PelicanPlatform/pelican/issues/1582

### CODE REVIEW

**Comment by CannonLock** [comment]
Screenshot 2024-10-25 at 12 56 18 PM

**Comment by h2zh** [comment]
image
Could you take a further look at this problem?

**Comment by CannonLock** [comment]
Had to close another issue when implementing the auth'd registry pages. 

Closes #1728

**Comment by h2zh** [comment]
There's a failed unbuntu test, could you take a second look

**Comment by CannonLock** [comment]
@h2zh Do you have any insights into the failure? This is a UI only change so it shouldn't effect any of the pelican tests unless the web build itself failed which I know isn't the case.

**Comment by jhiemstrawisc** [comment]
> @h2zh Do you have any insights into the failure? This is a UI only change so it shouldn't effect any of the pelican tests unless the web build itself failed which I know isn't the case.

@CannonLock, this is a known bad test at this point. If the failing `localcache` test is all that's blocking you, feel free to disregard it.

**Review by h2zh — APPROVED** [review]

**Pull request merged**
