### PR TITLE
Closes #275

### LINKED ISSUE #275: Missing favicon / title for Pelican webpage
It looks like there's some default icon being served -- should be a Pelican logo:

image

Additionally, the title of the page seems strange: after web UI initialization, shouldn't it be something like "Pelican Origin"?

### PR DESCRIPTION
**Pull request by CannonLock**
- Updates favicon.ico
- Changes metadata post login
- Closes #275

### CODE REVIEW

**Review by turetske — CHANGES_REQUESTED** [review]
I started up a web_ui using this branch and I'm still not seeing a logo, just the same triangle as before. So it doesn't seem to be solving the issue.

**Comment by CannonLock** [comment]
@turetske Don't forget to clear cache.

**Comment by turetske** [comment]
@CannonLock Oops! Thanks.

**Review by turetske — APPROVED** [review]
LGTM!

**Comment by bbockelm** [comment]
@CannonLock - before you merge, can you tweak the commit message to be a bit more descriptive?  I prefer understanding from the subject (the first line) what's going on without visiting GitHub.

**Pull request merged**
