### PR TITLE
Cleanup scheme for ft plugin output

### PR DESCRIPTION
**Pull request by joereuss12**
All changes fix issues listed in #808

### CODE REVIEW

**Comment by joereuss12** [comment]
Marked as draft since it still needs some testing

**Review by bbockelm — CHANGES_REQUESTED** [review]
Big picture change is to keep the time in the native go data structure for as long as possible.  Converting to integers too early loses too much data.

**Comment by joereuss12** [comment]
@bbockelm Next round of revisions are in, I moved the converting to `.Unix()` for the time stamps to be a tad later in the code. Let me know if you would like it to be even later than when I moved it.

**Review by jhiemstrawisc — APPROVED** [review]

**Comment by joereuss12** [comment]
@bbockelm same here too, are we good to merge? I think github wants your stamp of approval

**Comment by jhiemstrawisc** [comment]
Going to bypass branch protections on this one to get it in before Joe has to chase more merge conflicts. Thanks for taking care of this one, @joereuss12!

**Pull request merged**
