### PR TITLE
Have pelican plugin move files in parallel

### PR DESCRIPTION
**Pull request by joereuss12**
Now the plugin can move files just like handle_http does, starts up many workers and has a producer/consumer setup to download files in parallel.

### CODE REVIEW

**Comment by joereuss12** [comment]
This is still a work in progress so setting as a draft.

**Comment by joereuss12** [comment]
Smoke tests seem to show that this is working how it should, ready for review.

**Comment by bbockelm** [comment]
Haven't had time for a full review but to provide some early feedback:

https://github.com/PelicanPlatform/pelican/pull/674/files#diff-417e18b3b05bac37d2ebbc44d3be121f6026e5e4ab13e6400d0eb879027c5160R232-R240

This is approximately the design of the current parallel download when moving a directory.  I want to improve things, however, by having the result of individual transfers be returned on a channel.  That means there's a single for-loop that's both writing new tasks and reading results.

For example of what this would give us: right now, there's a hard synchronization -- all transfers must complete before the overall process can fail.  We know that we instead will want to fail all of them after the first transfer fails in the case of inputs.

**Review by jhiemstrawisc — APPROVED** [review]
LGTM

**Pull request merged**
