### PR TITLE
Add API Documentation to docs page

### PR DESCRIPTION
**Pull request by CannonLock**

### CODE REVIEW

**Comment by CannonLock** [comment]
Screenshot 2024-05-30 at 1 23 38 PM (2)

**Review by haoming29 — CHANGES_REQUESTED** [review]
Could you rename `api-docs.mdx` to snakecase `api_docs.mdx`? That's the pattern we already have for docs.

**Comment by CannonLock** [comment]
@haoming29 How about I move them all to hyphens? Snakecase in a web url is non standard and not recommended. 

https://developers.google.com/search/docs/crawling-indexing/url-structure#:~:text=Consider%20using%20hyphens%20to%20separate,(%20_%20)%20in%20your%20URLs.

**Comment by haoming29** [comment]
> @haoming29 How about I move them all to hyphens? Snakecase in a web url is non standard and not recommended.
> 
> https://developers.google.com/search/docs/crawling-indexing/url-structure#:~:text=Consider%20using%20hyphens%20to%20separate,(%20_%20)%20in%20your%20URLs.

Ah sure, as long as we keep them consistent

**Comment by CannonLock** [comment]
@haoming29 https://github.com/PelicanPlatform/pelican/pull/1414

**Review by haoming29 — APPROVED** [review]
LGTM

**Pull request merged**
