### PR TITLE
Rename `Federation.NamespaceUrl` to `Federation.RegistryUrl`

### LINKED ISSUE #388: Rename Federation.NamespaceUrl to Federation.RegistryUrl in config
Apparently `Federation.NamespaceUrl` isn't pointing to a namespace but instead to the registry. To be clear on this, we want to rename that config to  `Federation.RegistryUrl`. However, this may be a breaking change to client users, which we should proceed with caution.

### PR DESCRIPTION
**Pull request by haoming29**
Closes #388 

Per request, `Federation.NamespaceUrl` is preserved but marked as deprecated. User can still use this config but a warning message will should up if `Federation.NamespaceUrl` is used instead of `Federation.RegistryUrl`

### CODE REVIEW

**Review by bbockelm — CHANGES_REQUESTED** [review]
Two items, one which doesn't require follow-up:

1.  Please avoid spurious whitespace changes (there's a few whitespace-only changes in the parameters YAML file).  If these are necessary (i.e., someone else snuck them in and they are needed to pass the linter), please separate them out into a second commit.  No changes required now, however.
2. I'd like to see a small test that the warning message is actually emitted.  I won't require this for all changes along these lines but mostly want to make sure we have an example of testing log messages

For item (2), relevant examples from Google appear to be:
- https://github.com/sirupsen/logrus#testing
- https://maxchadwick.xyz/blog/testing-log-output-in-go-logrus

**Comment by haoming29** [comment]
> Two items, one which doesn't require follow-up:
> 
> 1. Please avoid spurious whitespace changes (there's a few whitespace-only changes in the parameters YAML file).  If these are necessary (i.e., someone else snuck them in and they are needed to pass the linter), please separate them out into a second commit.  No changes required now, however.
> 2. I'd like to see a small test that the warning message is actually emitted.  I won't require this for all changes along these lines but mostly want to make sure we have an example of testing log messages
> 
> For item (2), relevant examples from Google appear to be:
> 
> * https://github.com/sirupsen/logrus#testing
> * https://maxchadwick.xyz/blog/testing-log-output-in-go-logrus

Sorry about the whitespace changes. I think my VSCode plugin was formatting the yaml file on save and it's buried in my intended changes. This makes me wonder if we want to have a preferred yaml formatter for the project to make things more consistent? I was using [RedHat plugin](https://developers.redhat.com/products/vscode-extensions/overview). Otherwise, I will disable my local formatter.

**Comment by bbockelm** [comment]
> Sorry about the whitespace changes.

It's fine to do fixups -- feel free to keep your plugin enabled -- just please put them as a separate commit.  If you've not used it before, try using `git add --patch` to fine-tune the commits.  The `--patch` flag allows you to manage what's staged for the commit at a per-line level instead of per-file.

> This makes me wonder if we want to have a preferred yaml formatter for the project to make things more consistent?

We have the `check-yaml` precommit hook enabled.  Looks like the one you're using is just pickier.  There's others to choose from (see [this page](https://pre-commit.com/hooks.html), filter on `yaml`); I'm not sure if they can be made to match any VSCode formatter.

**Review by bbockelm — APPROVED** [review]
LGTM.  I like the new tests of logging -- hopefully the approach is useful in other places in the codebase.

**Pull request merged**
