### PR TITLE
Fixup a merge issue

### PR DESCRIPTION
**Pull request by CannonLock**

### CODE REVIEW

**Comment by CannonLock** [comment]
@haoming29 This removes some code that leaked in when I merge in previous changes. This code is now on the form.tsx page.

**Comment by haoming29** [comment]
> @haoming29 This removes some code that leaked in when I merge in previous changes. This code is now on the form.tsx page.
> 
> The test failure doesn't make much sense to me because I deleted the code that it is erroring on.

That failure could be a caching issue. Removed the GHA cache for macOS and see if that helps

**Comment by haoming29** [comment]
I seems like the error is in the base code, which should be the latest main, and it won't fix itself until we made the merge. Will merge this PR and see if this helps.

**Review by haoming29 — APPROVED** [review]
LGTM

**Pull request merged**
