### PR TITLE
Changes to dir listings in Pelican client

### PR DESCRIPTION
**Pull request by joereuss12**
This removes the need for namespaces to advertise "dirlisthost" since we can get that information with a PROPFIND request to the origin through a director redirect.

### CODE REVIEW

**Review by bbockelm — COMMENTED** [review]
Two things to consider as you work on this:

1.  Compatibility issues: What happens if you have a new client and an old director?  At first blush, it appears things would break.  You'll need to fall back gracefully to the old mechanism for finding the host.
2. Scale issues.  How can you make sure you only do the lookup of the host once per session.  Before, the director's namespace was queried once and then the interaction was with the origin.  Now, the director is queried for each stat and each directory listing.

**Comment by bbockelm** [comment]
@joereuss12 - what's the motivation around removing the webdav client and doing our own response parsing?

**Comment by joereuss12** [comment]
> @joereuss12 - what's the motivation around removing the webdav client and doing our own response parsing?

At first it was slightly unintentional but I am not entirely sure how to combine the webdav client with PROPFIND since PROPFIND will return the contents of the directory we request so it seems to be redundant with the webdav client. However, looking more into the source code for gowebdav, it seems that their "client.readdir" is already doing some sort of PROPFIND so I may need to rethink this approach.

**Comment by joereuss12** [comment]
Closing because #1111 solves this issue and is a better approach

**Pull request closed without merging**
