### PR TITLE
Fix Dockerfile goreleaser version fix for Issue #681

### PR DESCRIPTION
**Pull request by williamnswanson**
Fixing problems with the goreleaser fix from pr #684, since it didn't resolve the problem in Issue #681.

### CODE REVIEW

**Comment by williamnswanson** [comment]
I think that previously I had messed up the condition, something along the lines of comparing to the string "False" or the like instead of checking that IS_PR_BUILD was false.

**Comment by haoming29** [comment]
> I think that previously I had messed up the condition, something along the lines of comparing to the string "False" or the like instead of checking that IS_PR_BUILD was false.

Can you confirm that this fix result in a correct version number in the production container?

**Comment by williamnswanson** [comment]
After further testing, I'm fairly certain that this latest commit should properly run goreleaser with --snapshot for PRs and without it otherwise, but I can't tell whats going wrong with the ubuntu test:

```
--- FAIL: TestFedServePosixOrigin (0.20s)
    fed_serve_test.go:96: 
        	Error Trace:	/__w/pelican/pelican/cmd/fed_serve_test.go:96
        	Error:      	Received unexpected error:
        	            	Received bad status code in reply to server ping: 403. Expected 200,
        	            	github.com/pelicanplatform/pelican/server_utils.WaitUntilWorking
        	            		/__w/pelican/pelican/server_utils/server_utils.go:68
        	            	github.com/pelicanplatform/pelican/launchers.LaunchModules
        	            		/__w/pelican/pelican/launchers/launcher.go:162
        	            	github.com/pelicanplatform/pelican/cmd.TestFedServePosixOrigin
        	            		/__w/pelican/pelican/cmd/fed_serve_test.go:92
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1650
        	Test:       	TestFedServePosixOrigin
FAIL
```

**Comment by haoming29** [comment]
> After further testing, I'm fairly certain that this latest commit should properly run goreleaser with --snapshot for PRs and without it otherwise, but I can't tell whats going wrong with the ubuntu test:
> 
> ```
> --- FAIL: TestFedServePosixOrigin (0.20s)
>     fed_serve_test.go:96: 
>         	Error Trace:	/__w/pelican/pelican/cmd/fed_serve_test.go:96
>         	Error:      	Received unexpected error:
>         	            	Received bad status code in reply to server ping: 403. Expected 200,
>         	            	github.com/pelicanplatform/pelican/server_utils.WaitUntilWorking
>         	            		/__w/pelican/pelican/server_utils/server_utils.go:68
>         	            	github.com/pelicanplatform/pelican/launchers.LaunchModules
>         	            		/__w/pelican/pelican/launchers/launcher.go:162
>         	            	github.com/pelicanplatform/pelican/cmd.TestFedServePosixOrigin
>         	            		/__w/pelican/pelican/cmd/fed_serve_test.go:92
>         	            	testing.tRunner
>         	            		/usr/local/go/src/testing/testing.go:1595
>         	            	runtime.goexit
>         	            		/usr/local/go/src/runtime/asm_amd64.s:1650
>         	Test:       	TestFedServePosixOrigin
> FAIL
> ```

Yeah that's a flaky test. Re-run for the fifth time make it successful

**Pull request merged**
