### PR TITLE
Added tests for the three functions in origin_api.go

### PR DESCRIPTION
**Pull request by turetske**
Tests tokens with various scopes for the `VerifyAdvertiseToken` function
	Tests the string created from `GetIssuerURL`
	Tests token creation using the `CreateAdvertiseToken` function
	Also adjusts the mocked cache in redirect_test.go to be used by both test files

### CODE REVIEW

**Comment by jhiemstrawisc** [comment]
@turetske Just a heads up, we need to meddle with some of these tokens, and ultimately the functions that verify them (and their tests) soon. See issue #159. 

I think all this is okay for now, but we might have to come back to revisit at some point soon.

**Comment by turetske** [comment]
> @turetske Just a heads up, we need to meddle with some of these tokens, and ultimately the functions that verify them (and their tests) soon. See issue #159.
> 
> I think all this is okay for now, but we might have to come back to revisit at some point soon.

@jhiemstrawisc Okay. I don't know enough about tokens to understand issue #159, but I will absolutely take your word for it.

**Comment by bbockelm** [comment]
@turetske - is there a corresponding issue for this PR?

**Comment by turetske** [comment]
@bbockelm Yeah, it's #119. I couldn't get started on my last v1.0 issue without clarification so I decided to tackle one of the unit tests issues I created. And then decided might as well test the whole file rather than one function.

**Pull request merged**
