### PR TITLE
Director cli hookup

### PR DESCRIPTION
**Pull request by jhiemstrawisc**
PR https://github.com/PelicanPlatform/pelican/pull/7 introduced a framework for including the Director in the Pelican CLI, toward making all Pelican services available under a single binary. This commit extends that PR to hook the Director package up to the CLI, the Pelican's configuration mechanisms, and to actually sort out a few bugs related to the untested director code.

It should be noted that there are currently a few hacks in the code that need clearing up before any merge, but as of now the commit makes the following possible:
`pelican director serve --cache-port 8000` 
This will serve the Director's cache-redirection service on port 8000 using a gin engine. When we've figured out how to handle Origin redirects and implemented an origin-redirect service, we'll be able to do:
 `pelican director serve --cache-port 8000 --origin-port 8001` 
to split apart the two endpoints.

As for the local lint... I'm still trying to figure out how to shut that feature off in my editor. Sorry for the noise!

### CODE REVIEW

**Comment by bbockelm** [comment]
@jhiemstrawisc - there's still the merge conflict left to resolve.  What else remains on the punch list?

**Comment by jhiemstrawisc** [comment]
AFAIK, it should just be the merge conflict. I left that for myself to do this morning. I'm still waiting for the updates in topology (pretty sure that PR just needs a rebase and merge), but I was able to test with the new draft JSON that has the correct ports -- and ospool origin.

Once I get this merged, I'll start working on a deployment.

**Comment by jhiemstrawisc** [comment]
@bbockelm I think this is ready

**Review by bbockelm — APPROVED** [review]
Fantastic!  Let's get this out the door.

**Pull request merged**
