### PR TITLE
First step toward self-testing: configure authorization

### PR DESCRIPTION
**Pull request by bbockelm**
The embedded XRootD server needs to be able to configure authorization for the built-in issuer.

This PR does exactly that -- reading in the (optional) admin-provided `scitokens.cfg` file, augmenting it with the builtin issuer, and then writing out the newly-generated configuration into the runtime directory.

Comes with fairly comprehensive unit tests -- it just doesn't have any user-facing changes.

### CODE REVIEW

**Comment by jhiemstrawisc** [comment]
@bbockelm I think I mostly understand what's going on here, but I'm not sure how I can inspect the final output of the generated `scitokens-generated.cfg`. From reading the code, I'd expect serving a rootly origin to emit such a file in `/run/pelican/xrootd`.

It doesn't look like any of the new functions in `xrootd/authorization` are called outside of the tests. Perhaps all this code is reached through some mechanism I'm unaware of, or am I mistaken?

**Comment by bbockelm** [comment]
Right now, the code indeed isn't reachable beyond the tests.  My thinking is to get the infrastructure merged now and then start working on the periodic self-test code.

**Review by jhiemstrawisc — CHANGES_REQUESTED** [review]
Just a few small things, otherwise LGTM

**Review by jhiemstrawisc — APPROVED** [review]
LGTM

**Pull request merged**
