### PR TITLE
Fix issuer for self-monitoring and scitokens issuer name

### LINKED ISSUE #1275: Pelican origin/cache uses external issuer for self-tests
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- Origin
- Cache

**Describe the bug**
_A clear and concise description of what the bug is._

Pelican allows user to use an external issuer for authentication/authorization. However, when doing so, the issuer for self-testing is also changed to the external issuer, which invalidate token for self-tests because that's generating with the internal issuer of the server.

We should leave the internal issue as-is if the user set an external issuer.

### PR DESCRIPTION
**Pull request by haoming29**
Fixes #1275

### CODE REVIEW

**Review by turetske — CHANGES_REQUESTED** [review]
Can you create a test to show that the issuers are generated correctly in xrootd/authorization_test.go?

**Comment by haoming29** [comment]
> Can you create a test to show that the issuers are generated correctly in xrootd/authorization_test.go?

There's existing test coverage and I updated the test file to reflect the change: `xrootd/resources/test-scitokens-monitoring.cfg`

**Comment by turetske** [comment]
> > Can you create a test to show that the issuers are generated correctly in xrootd/authorization_test.go?
> 
> There's existing test coverage and I updated the test file to reflect the change: `xrootd/resources/test-scitokens-monitoring.cfg`

Ah, okay. I missed that somehow.

**Review by turetske — APPROVED** [review]
LGTM! Ran it locally just to be sure.

**Pull request merged**
