### PR TITLE
Implement recursive uploads

### PR DESCRIPTION
**Pull request by joereuss12**
First draft of recursive uploads. This will go through a directory and upload every file to the destination. The only problem is that it will not maintain the same directory structure since I could not find a way to have PUT work with directories.

### CODE REVIEW

**Comment by joereuss12** [comment]
@bbockelm Would you like me to look more into somehow keeping the directory structure on the server side? As of now, it only spits all of the files into the specified directory on the origin because I could not figure out how to do a client side PUT with directories.

**Comment by joereuss12** [comment]
Marking this ready for review. Cannot create a unit test because it requires a director to be spinning so it can find the `namespace.DirListHost`. Therefore, I will just wait to create an end-to-end test for it when Emma completes her "federation in a box".

**Comment by bbockelm** [comment]
@joereuss12 - there are some conflicts to fix up here.

**Review by turetske — APPROVED** [review]
Approved when merge conflicts are resolved

**Pull request merged**
