### PR TITLE
Stash plugin abort early branch

### PR DESCRIPTION
**Pull request by joereuss12**
If some sort of failure occurs during download, the plugin now will immediately write the output file and exit (1 or 11 depending on if the error is retryable). Also, I was having issues with param_generator making param_struct.go have an extra new line at the bottom whenever it was generated. Go-linter does not like this so I have to `git restore` it every time I want to commit. This should fix that (hopefully it's not just me having this issue).

### CODE REVIEW

**Comment by haoming29** [comment]
@joereuss12 Saw you marked this as v7.5. For the extra whitespace at the EDF, I also had the same issue but I think goreleaser also doesn't like it with a dirty commit, and it cause failure of running goreleaser in GHA. Do you think we should cherry pick that small fix and merge in before you roll out 7.4?

**Comment by joereuss12** [comment]
@haoming29 Yeah we are working on that issue of a dirty commit right now before this fix is even in place. I don't think this will make too much of a difference if it is in 7.4 or 7.5. The dirty commit seems like it's unrelated after some digging.

**Comment by joereuss12** [comment]
@haoming29 Nevermind, seems like you are actually correct

**Comment by joereuss12** [comment]
This issue is now solved by #674

**Pull request closed without merging**
