### PR TITLE
Namespace UI

### PR DESCRIPTION
**Pull request by CannonLock**
- Show namespace capabilities
- Show interaction between namespace and server capabilities

### CODE REVIEW

**Comment by CannonLock** [comment]
Screenshot 2024-11-14 at 4 10 46 PM (2)

**Comment by CannonLock** [comment]
Closes https://github.com/PelicanPlatform/pelican/issues/1724

**Comment by CannonLock** [comment]
New namespace card with the nested capabilities. Should give easy insight to what caches and servers are open to this namespace. 

Screenshot 2024-11-18 at 3 36 39 PM (2)

**Comment by h2zh** [comment]
> New namespace card with the nested capabilities. Should give easy insight to what caches and origins provide what capabilities for this namespace.
> 
> Screenshot 2024-11-18 at 4 12 43 PM (2)

There are multiple "issuer" showing up here. I think it'd be better to differentiate them here in case causing further confusion. Here are my two cents to avoid semantic overload:

1. Change "issuer" under "token generation" to another word, like "generator". Also change its occurrences everywhere else
2. Add tool-tip to "issuer" and "generator", explaining their difference in Pelican project. For example:
- Token Generator: a server that performs the technical task of creating the token
- Token Issuer: a server as a trusted authority that vouches for the authenticity of the token
 
Could you take a quick look and share your thoughts on the necessity of this change @jhiemstrawisc

**Review by h2zh — APPROVED** [review]

**Pull request merged**
