### PR TITLE
Fix bug when director returns 404 for PROPFIND

### PR DESCRIPTION
**Pull request by joereuss12**
Found a bug when we try to PROPFIND against an outdated director, the director returns a 404 not found (because it redirects to a cache and that cache cannot find the object to PROPFIND so it returns a 404). When this happens the client returns just the error and not the response. Therefore, the fix is to check if we fail querying the director with a PROPFIND, we check if the namespace has a dirlisthost. If dirlisthost is present, we continue and otherwise, we fail. We'll need to eventually create a way to test against outdated directors but for now, we'll stick to this band-aid.

### CODE REVIEW

**Comment by joereuss12** [comment]
made issue #1255 so we can remember to test this. Since it is so close to release (and this is a significant bug) and because we currently don't have the framework to test against old directors, we should put this fix out in a patch release and revisit making tests for this in the near future.

**Comment by bbockelm** [comment]
Instead of blanket covering _all_ errors, can we just target the error we know old directors to do (404?)?

**Comment by joereuss12** [comment]
> Instead of blanket covering _all_ errors, can we just target the error we know old directors to do (404?)?

Implemented just now

**Review by jhiemstrawisc — APPROVED** [review]

**Comment by joereuss12** [comment]
@turetske are you able to throw this in the patch release as well?

**Pull request merged**
