### PR TITLE
Strip "Bearer " from authz query and header if they're present

### PR DESCRIPTION
**Pull request by jhiemstrawisc**
I noticed while testing XRootD's ability to use a Pelican director as its redirector (defined via the `pss.origin` directive), that XRootD will take a token passed to it via an Authorization header and convert it directly into an authz URL query that gets passed to the director. For the director to return a valid redirect URL, the "Bearer " prefix must be stripped.

### CODE REVIEW

**Comment by bbockelm** [comment]
@jhiemstrawisc - can you add a simple regression / unit test here?  Even if it's only capturing `getAuthzEscaped` and not the end-to-end, it'd capture a future regression.

**Review by bbockelm — CHANGES_REQUESTED** [review]
Forgot to give a formal review, only typed the comment -- please add a simple regression test here.

**Review by bbockelm — APPROVED** [review]
I'm a little suspicious about automatically converting the
```
Authorization: token1234
```

(i.e., when it's missing the `Bearer` prefix)  Did we actually hit such a case?

Regardless, I think it's fine to go forward with it.

**Comment by jhiemstrawisc** [comment]
Is the issue that we want to some kind of failure in the case that a header-embedded token is missing the `Bearer ` prefix? I have indeed managed to trigger XRootD to send an `Authorization: Basic blah` header, although I'm not sure what I did to achieve that.

**Pull request merged**
