### PR TITLE
Remove --snapshot tag from goreleaser command in Dockerfile

### PR DESCRIPTION
**Pull request by williamnswanson**
[For Pelican Issue #681](https://github.com/PelicanPlatform/pelican/issues/681)

### CODE REVIEW

**Comment by haoming29** [comment]
Sorry about the linter changes and causes failure on your branch. Could you rebase against the latest main? The linter fix is in place.

**Review by haoming29 — APPROVED** [review]
LGTM

**Comment by haoming29** [comment]
@williamnswanson  Looks like the build failed due to missing GitHub tokens. Looking at the doc, it seems that running `goreleaser` by default will build and try to release the build, which we don't want. We only want to build the project locally in the container. So we should use `goreleaser build -- clean`

**Comment by haoming29** [comment]
Ahh. That GHA runs on both PR and release with a tag. For PR, we don't have a tag attached to the branch, and goreleaser is unhappy about it. It's going to be a bit tricky for docker build to be compatible with both PR build and release build. You'll need to pass `${{ github.event_name != 'pull_request' }}` from GHA that build the prod image to Dockerfile.

**Comment by williamnswanson** [comment]
Let me know if you want the conditional in the Dockerfile to be arranged differently.

**Comment by haoming29** [comment]
> Let me know if you want the conditional in the Dockerfile to be arranged differently.

LGTM! Thanks for taking care of it.

**Pull request merged**
