### PR TITLE
Add rate-limiter to the login endpoint

### LINKED ISSUE #711: Add rate limiting to various login endpoint

### PR DESCRIPTION
**Pull request by haoming29**
Closes #711 

To test, build locally and run your any of your Pelican server and go to `https://<hostname>:<port>/view/login/index.html`

Hit `Confirm` button without typing any username. If you hit it slowly (not double click), then you should get 400 error. If you double-click or triple click, then you should get 429 error indicating too many requests.

### CODE REVIEW

**Comment by bbockelm** [comment]
Could you switch to `golang.org/x/time/rate` perhaps?  I was planning on using it elsewhere:

https://github.com/PelicanPlatform/pelican/pull/705/files#diff-4f90d3c881e24d44c38cce40e200654acfd79622cf17bea2fd7b557aa9c58bc1R49-R62

Avoids the redis dependency.

**Comment by haoming29** [comment]
@bbockelm It should be doable to use `golang.org/x/time/rate` but `gin-rate-limit` is more flexible as it limits the rate by a key per request (IP in our case). I didn't find the built-in rate package to have the equivalent which means we need to build the `key` support ourselves.

**Comment by bbockelm** [comment]
Gotcha.  How much larger does the binary become with this new dependency?

**Comment by haoming29** [comment]
> Gotcha. How much larger does the binary become with this new dependency?

The size of the built binary didn't seem to change. It's `42.1MB` for both `main` branch and my feature branch. But the size seems to be doubled compared to the `7.5.0` release artifact.

**Review by joereuss12 — APPROVED** [review]
LGTM, also I really like how you always say how to test it. I had a joy of a time spamming that button

**Pull request merged**
