### PR TITLE
Swagger docs

### PR DESCRIPTION
**Pull request by CannonLock**
Add swagger doc page to:

- /view/api/docs/
- /api/v1.0/docs

### CODE REVIEW

**Comment by CannonLock** [comment]
Closes #353

**Comment by haoming29** [comment]
@CannonLock Why would we need to upgrade node version to 20 for Swagger UI to work? Is there a specific package the requires higher-version than 18?

**Comment by CannonLock** [comment]
@haoming29 Website prerender requires Node 20, unsure why but the fileReadSync returns undefined in node 18.

**Comment by haoming29** [comment]
Not sure why but I got this error message:
```console
> next build

   ▲ Next.js 14.0.3

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...

./components/graphs/Graph.tsx
112:8  Warning: React Hook useEffect has a missing dependency: 'setData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Collecting page data ...
   Generating static pages (0/11) ...
/webapp/.next/server/app/api/docs
/webapp/.next/server/app/api/docs
/webapp/.next/server/app/api/docs
/webapp/.next/server/app/api/docs
Error: ENOENT: no such file or directory, open '/swagger/pelican-swagger.yaml'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at d (/webapp/.next/server/app/api/docs/page.js:12:328809)
    at em (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Array.toJSON (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
    at stringify (<anonymous>)
    at eE (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132044)
    at eR (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132487)
    at Timeout._onTimeout (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/swagger/pelican-swagger.yaml'
}
Error: ENOENT: no such file or directory, open '/swagger/pelican-swagger.yaml'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at d (/webapp/.next/server/app/api/docs/page.js:12:328809)
    at em (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Array.toJSON (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
    at stringify (<anonymous>)
    at eE (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132044)
    at eR (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132487)
    at Timeout._onTimeout (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/swagger/pelican-swagger.yaml'
}

Error occurred prerendering page "/api/docs". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, open '/swagger/pelican-swagger.yaml'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at d (/webapp/.next/server/app/api/docs/page.js:12:328809)
    at em (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Array.toJSON (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
    at stringify (<anonymous>)
    at eE (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132044)
    at eR (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132487)
    at Timeout._onTimeout (/webapp/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267)
   Generating static pages (2/11) 
   Generating static pages (5/11) 
   Generating static pages (8/11) 
 ✓ Generating static pages (11/11) 

> Export encountered errors on following paths:
	/api/docs/page: /api/docs
make: *** [web_ui/frontend/out/index.html] Error 1
```

**Comment by CannonLock** [comment]
@haoming29 Are you running Node 20?

**Comment by haoming29** [comment]
> @haoming29 Are you running Node 20?

I believe so? I ran it as `make web-build USE_DOCKER=1`

**Review by haoming29 — APPROVED** [review]
LGTM! Confirmed that I can run `make web-build` both with `USE_DOCKER=1` and without it, and the Swagger UI looks correct to me.

**Pull request merged**
