### PR TITLE
frontend for deleting register namespace

### PR DESCRIPTION
**Pull request by h2zh**
image
This feature enables user to delete their approved namespace in the registry.
Address issue #1593

### CODE REVIEW

**Comment by CannonLock** [comment]
@h2zh Looks good, I pushed the two changes as they were quick. 

Two things:

- I don't have the alert yet in the global context so you have to create the alertportal to set an alert and have it shown

- Run `npm run format:fix` before pushing to fix any js linter issues

**Review by CannonLock — APPROVED** [review]

**Review by CannonLock — APPROVED** [review]
Approved good catch thank you!

**Comment by CannonLock** [comment]
@h2zh Can you run `npm run format:fix` at web_ui/frontend so that the linter error is resolved?

**Comment by h2zh** [comment]
sure, on it @CannonLock

**Comment by h2zh** [comment]
I ran that command but seems like nothing changes. Could I visit your cubicle to see what's the issues displayed on your side? @CannonLock

**Pull request merged**
