### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by CannonLock**
Adds Copyright info to the Typescript pages
Redirects root to /view
Adds some basic graphs to the initial view on login with xrootd data

### CODE REVIEW

**Review by bbockelm — APPROVED** [review]
@CannonLock - going to approve this just to get things going.

However, there's two issues:
1. We need to do a better job handling the "no data" use case.  Default to zero, spinning beachball, something better than the placeholder now.
2. We don't appear to require authorization for the splash page itself... if you go to some part of the UI _besides_ the code initialization page, it'll happily serve up the regular UI.  Instead, we should require the password to be set (via redirect to the code page) or require users to login.
   - Additionally, we should add a "logout" page.

I'm OK with both being done in a follow-up PR, however.

**Comment by bbockelm** [comment]
Oh!  And forgot to mention: I did a quick rebase to fix up the lack of line endings that your editor is generating.  Please review settings for whatever editor you use ... those shouldn't occur!

**Comment by CannonLock** [comment]
@bbockelm I iterated past both of those options in favor of the text which I found more informative. 

Screenshot 2023-09-06 at 8 16 25 AM (2)

**Comment by CannonLock** [comment]
How do you feel about this?

**Pull request merged**
