### PR TITLE
Return config values with types for /config API

### LINKED ISSUE #394: Updates `/config` API to include type information
It is going to be necessary for the eventual Config write api to have type information attached. For complex types it would also be great to have a pointer to the type in the go documentation. 

For instance there is currently a [`duration` type](https://pkg.go.dev/time#Duration) the web ui will have to be aware of as it seems that it is a int type but accepts string inputs. 

I think the best thing logically is for the web ui to take care of any parsing to make things human readable so for the duration instance I will always expect time in nanoseconds and always return the same, but will make the user interface show the string parse version.

### PR DESCRIPTION
**Pull request by haoming29**
Closes #394 

This PR should NOT be merged before 7.3 release. The UI part is not meant to work with this updated structure now.

### CODE REVIEW

**Review by joereuss12 — COMMENTED** [review]
LGTM, just need to fix those merge conflicts. Might not need to worry about it too soon though since we can't merge until 7.3 is released. I'll take another look at it once we release and Cannon updates the web ui. I won't full on approve it yet until it is tested with the new release.

**Comment by bbockelm** [comment]
@haoming29 - is this still valid?  Looks like there's merge conflicts but approved at the review level.

**Comment by haoming29** [comment]
> @haoming29 - is this still valid? Looks like there's merge conflicts but approved at the review level.

I think this became a dangling PR because I was told to include the type info of the parameters in `/config` API  during one of the standup and thought it was urgent so I implemented it, had a PR fairly quickly and realized this is for the new feature where we allow users to modify config parameter values through web UI. And unfortunately, the change of the data structure of the `/config` API in this PR will break frontend rendering, so I was holding off merging this.

I saw two ways to proceed. We can 1. prioritize making changes at frontend to be compatible with this new data structure (and not necessarily implement the "write config values through web ui" yet) or 2. Close this PR and re-open when we think we need it.  I'd like to know how @CannonLock feel about this.

**Comment by CannonLock** [comment]
@haoming29 Can you merge with main? Then I will put the web ui parts on top of this.

**Comment by haoming29** [comment]
> @haoming29 Can you merge with main? Then I will put the web ui parts on top of this.

Working on it at the end of the day yesterday and the merge caused a seg fault. Will fix it ASAP today.

**Review by joereuss12 — APPROVED** [review]
LGTM

**Comment by haoming29** [comment]
> LGTM

Hey @joereuss12 . Thanks for the approval! I think I will wait for #589 to merged in first, as I based off this branch to fix the bug on main. I'm also investigating a seg fault on my local dev so please hold off review it. I will let you know when it's ready. Thanks!

**Comment by joereuss12** [comment]
Sounds good, just let me know!

**Comment by haoming29** [comment]
> Sounds good, just let me know! That's why I didn't merge yet, wasn't super sure

@joereuss12 Now I think we should be good to go 🎉

**Pull request merged**
