### PR TITLE
Update parameters documentation

### LINKED ISSUE #578: Improve parameter documentation
The [parameter documentation page](https://docs.pelicanplatform.org/parameters) could use some improving.

0.  Provide a search box at the top where people can live filter for parameters they are interested in.  Should contain buttons that filter quickly on a specific component.
1. Make each parameter description more of a self-contained card.
2.  Add visual cues for the different components instead of a rendered list.  Similarly, add some structure around the type and default.  The type should be rendered human friendly ("integer", not "int") with tooltips
3. Might play around with having the sub-parameters in a collapsable structure so you can easily suppress ones you're not interested in.  Not sure if this would render well.
4. Add a sentence to the top describing what the page is.

### PR DESCRIPTION
**Pull request by CannonLock**
Closes #578

### CODE REVIEW

**Comment by CannonLock** [comment]
Screenshot 2024-01-22 at 11 52 22 AM (2)

**Comment by haoming29** [comment]
@CannonLock Just to confirm, is this the PR that closes #578 ? or just part of it? Seems like there's still a good amount of work to be done to effectively close all the tasks listed in the issue.

**Comment by CannonLock** [comment]
@haoming29 Yeah, sorry for the lack of verbosity. 

Alperen closed out 1, and 2 with the PR here -> https://github.com/PelicanPlatform/docs/pull/3

This is to close out 4, and we will have 0 remaining which I have commented there.

**Review by haoming29 — APPROVED** [review]
LGTM!

**Pull request merged**
