### PR TITLE
Add Parameters page and order/name docs

### LINKED ISSUE #219: Documentation
Create documentation page auto generated from the parameters file.

### PR DESCRIPTION
**Pull request by CannonLock**
Closes #219

### CODE REVIEW

**Comment by CannonLock** [comment]
Screenshot 2023-11-06 at 3 26 16 PM (2)

**Comment by CannonLock** [comment]
I realize there is not sidebar selection as I generated with JSX but this is a incoming feature of Nextra so I didn't bother implementing myself.

**Comment by CannonLock** [comment]
Also the magic to build the new parameters file happens on the website, see:

https://github.com/PelicanPlatform/docs/commit/0fa80fe1cb83cba36143d61ed6ab2ea73926661f

**Review by turetske — CHANGES_REQUESTED** [review]
When I load up the page, the first parameter I see is "ThisIsATestConfig" which doesn't seem to actually exist in the code as a param and has the same description as "Debug".

**Comment by CannonLock** [comment]
@turetske I put in a placeholder, the real file gets added at website build. 

Proof: https://docs.pelicanplatform.org/static/parameters.json

**Review by turetske — APPROVED** [review]
LGTM!

**Pull request merged**
