### PR TITLE
Added token checking for prometheus metrics

### PR DESCRIPTION
**Pull request by turetske**
-- Added a checkPromToken function in prometheus.go to check the tokens
    -- Added unit tests for checking the metrics
    -- Fixed missing "Bearer " in redirect_test

### CODE REVIEW

**Comment by bbockelm** [comment]
@jhiemstrawisc - I'd like you to pick up the review on this one.  One thing to check is that the graphs in the web UI that @CannonLock is working on continues to work.

@turetske - on its face, the approach looks correct (I'll let Justin dig into the details).  One thing this does *not* do is enable tokens that would be coming from the federation (but it's OK to do that part as a separate PR).  For the latter, you can get the JWKS information from the auto-discovery URL:

```
$ curl https://osg-htc.org/.well-known/pelican-configuration
{
  "director_endpoint": "https://director-caches.osgdev.chtc.io",
  "namespace_registration_endpoint": "https://registry.osgdev.chtc.io",
  "jwks_uri": "https://osg-htc.org/osdf/public_signing_key.jwks",
  "collector_endpoint": "condor://osdf-collector.osg-htc.org"
}
```

The `jwks_uri` is going to hold the public key for the Prometheus scraper from the federation.  The issuer in the token from the federation (in this example) is `https://osg-htc.org/`.

**Comment by bbockelm** [comment]
Oh - one other thing I just spotted.  @turetske - can you make sure to work in your own fork and not create branches in the main repo for features?

**Comment by turetske** [comment]
> Oh - one other thing I just spotted. @turetske - can you make sure to work in your own fork and not create branches in the main repo for features?

Yep. Starting to do that.

In regards to the using federation tokens, (I'm still fuzzy on tokens in general, so forgive me if this is a silly question) would it just be a case of changing where it's pulling the jwks it's verifying against from? Getting it from the auto-discovery url rather than `config.GetOriginJWKS`? Or would there be more to do?

**Comment by bbockelm** [comment]
> In regards to the using federation tokens, would it just be a case of changing where it's pulling the jwks it's verifying against from? Getting it from the auto-discovery url rather than config.GetOriginJWKS? Or would there be more to do?

Yes.  You'd look at the `iss` ("issuer") attribute and decide where to pull the public key from.  So, somewhere in the existing code there will be a conditional to see if the issuer was the federation itself...

**Comment by turetske** [comment]
Closing PR in order to redo as a fork

**Pull request closed without merging**
