### PR TITLE
Provide ConfigureOriginAPI a cancel context that can be cancelled on shutdown

### LINKED ISSUE #350: Provide ConfigureOriginAPI a context object that can be cancelled on shutdown
See https://github.com/PelicanPlatform/pelican/pull/305#discussion_r1385261106

We want to gracefully handle the exit logic for origin's director-health-report timeout timer. Rather than using signal handlers, we want to use context object and call the context when origin is shutting down.

### PR DESCRIPTION
**Pull request by haoming29**
Closes #350

### CODE REVIEW

**Comment by haoming29** [comment]
I solved the merge conflict, but I couldn't find where `cmd_serve` lives. @turetske Could you point me to it? Thanks

**Review by turetske — CHANGES_REQUESTED** [review]
@haoming29 It should be in cmd/cache_serve.go if you've rebased off of main since yesterday. And I just realized I made a spelling mistake in my previous review, I'm sorry about that.

**Comment by haoming29** [comment]
> @haoming29 It should be in cmd/cache_serve.go if you've rebased off of main since yesterday. And I just realized I made a spelling mistake in my previous review, I'm sorry about that.

No worries. Will add it

**Review by turetske — APPROVED** [review]
LGTM!

**Pull request merged**
