### PR TITLE
Correct parsing of scitokens.cfg with empty audience_json value

### LINKED ISSUE #601: scitokens.conf parsing dies when there is no `audience_json` option
When Xrootd.ScitokensConfig is set to an existing scitokens.conf file and that file does not have an `audience_json` option, pelican dies at startup with the error
```
Error: Failed to create scitokens configuration for the cache: Failed to load scitokens configuration at /run/stash-cache-auth/scitokens.conf: Unable to parse audience_json from /run/stash-cache-auth/scitokens.conf: unexpected end of JSON input
```
however, you can also have a scitokens.conf with an `audience` option that is just a comma-and-space-separated list. Here is a typical scitokens.conf file for a cache generated by topology:
```
[Global]
audience = GLOW, HCC, IceCube, NRP, OSG, PATh, UCSD

[Issuer https://ap20.uc.osg-htc.org:1094/ospool/ap20]
issuer = https://ap20.uc.osg-htc.org:1094/ospool/ap20
base_path = /ospool/ap20

[Issuer https://ap21.uc.osg-htc.org:1094/ospool/ap21]
issuer = https://ap21.uc.osg-htc.org:1094/ospool/ap21
base_path = /ospool/ap21

[Issuer https://ap22.uc.osg-htc.org:1094/ospool/ap22]
issuer = https://ap22.uc.osg-htc.org:1094/ospool/ap22
base_path = /ospool/ap22

[Issuer https://ap22.uc.osg-htc.org:1094/ospool/ap22]
issuer = https://ap22.uc.osg-htc.org:1094/ospool/ap22
base_path = /ospool/ap22/data,/ospool/uc-shared/project

[Issuer https://chtc.cs.wisc.edu/icecube]
issuer = https://chtc.cs.wisc.edu/icecube
base_path = /icecube

[Issuer https://chtc.cs.wisc.edu]
issuer = https://chtc.cs.wisc.edu
base_path = /chtc

[Issuer https://osg-htc.org/ospool/uc-shared]
issuer = https://osg-htc.org/ospool/uc-shared
base_path = /ospool/uc-shared/project

[Issuer https://osg-htc.org/ospool]
issuer = https://osg-htc.org/ospool
base_path = /ospool/PROTECTED,/s3.amazonaws.com/us-east-1,/s3.amazonaws.com/us-west-1

[Issuer https://path-cc.io]
issuer = https://path-cc.io
base_path = /path-facility/data,/path-facility/development/data/,/path-facility/projects,/path-facility/development/projects/

[Issuer https://scitokens.org/hcc]
issuer = https://scitokens.org/hcc
base_path = /hcc

[Issuer https://scitokens.org/osg-connect]
issuer = https://scitokens.org/osg-connect
base_path = /
restricted_path = /osgconnect

[Issuer https://t.nationalresearchplatform.org/burnpro3d]
issuer = https://t.nationalresearchplatform.org/burnpro3d
base_path = /ndp/burnpro3d

[Issuer https://t.nationalresearchplatform.org/ucsdphysics]
issuer = https://t.nationalresearchplatform.org/ucsdphysics
base_path = /ucsd/physics

[Issuer https://t.nationalresearchplatform.org/xenon]
issuer = https://t.nationalresearchplatform.org/xenon
base_path = /nrp/protected/xenon-biggrid-nl/

[Issuer https://token.nationalresearchplatform.org/modis]
issuer = https://token.nationalresearchplatform.org/modis
base_path = /nrp/protected/sio/MODIS_Aqua_microphysics_images/
```

### PR DESCRIPTION
**Pull request by bbockelm**
The INI library always returns a key when there's a lookup -- if the key isn't in the section, the returned object is a valid key with an empty value.  When this empty string was being parsed as JSON, an error was thrown.

Fixed the conditional to check for a non-empty key and added a short unit test.

Note this branch builds on top of #594.

Fixes #601

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
Looks like you're missing a package used in the test (`slices`) but otherwise it looks fine.

**Comment by bbockelm** [comment]
Bah.  Looks like the `slices` package was introduced in 1.21.0 and we're on 1.20.0!

**Comment by haoming29** [comment]
@bbockelm Replaced `slices` by `reflect.DeepEqual`. Hopefully GHA is happy.

**Comment by haoming29** [comment]
I think the second round of tests failed due to flaky test in a random way, but it seems to be still part of the testing on xrootd maintenance routine that caused the failure: https://github.com/PelicanPlatform/pelican/actions/runs/7413081964/job/20171285018

**Pull request merged**
