### PR TITLE
Add bearer token config to HTTP backends for Globus compat

### LINKED ISSUE #1413: Pass Globus token location to xrootd

### PR DESCRIPTION
**Pull request by jhiemstrawisc**
This adds a generic config for adding an bearer token to the `Authorization` header on requests from the origin to an http backend. In particular, this is needed for Globus collections.

Closes #1413

### CODE REVIEW

**Comment by jhiemstrawisc** [comment]
@haoming29, when I was deciding whether to export the `origin.GlobusActivated` field or the general `origin.isExportActivated` function, I settled on the former because the collections don't yet support multiple collections in `xrootd_config.go` where we only look at the first collection in the exports slice. If you think I should change that, let me know.

**Comment by jhiemstrawisc** [comment]
Also, thoughts on the security warning? Outside of exporting the `origin.GlobusTokenFileExt` var, I haven't changed the way this directory is handled.

**Comment by haoming29** [comment]
> Also, thoughts on the security warning? Outside of exporting the `origin.GlobusTokenFileExt` var, I haven't changed the way this directory is handled.

Yeah, but this should be from the previous code I wrote. We are reading the user-provided `cid` from query param, but this is the only way to match the collection. I've added basic path cleaning and security check to avoid path traversal. Let me know if this is still a concern.

**Review by haoming29 — APPROVED** [review]
LGTM. It makes sense to me to make the three variable public instead of exporting that `isExportActivated` function because that function relies on internal struct to work and publishing this may impose null-pointer risk

**Comment by haoming29** [comment]
@jhiemstrawisc I just hand-tested and realized I need to change ownership of the token path to xrootd. To push things through, I've patched the fix to this PR. Feel free to take a look

**Pull request merged**
