### PR TITLE
Add default config.d locations to RPM packaging

### LINKED ISSUE #1660: RPM packaging should use config.d by default
Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [X] Origin
- [X] Cache
- [ ] Other (please give the detail)

**Is your feature request related to a problem? Please describe.**

Ahead of the OSG 24 upgrade, we should settle on a more admin-friendly configuration layout using multiple `config.d` dirs

**Describe the solution you'd like**

- Treat `/etc/pelican/pelican.yaml` as the entrypoint. Should be marked as config but will be overwritten by package updates
- Create `/usr/share/pelican/config.d`: this is where default config will go and any edits will be destroyed upon package update
- Create `/etc/pelican/config.d`: this is where admin config will go, which will remain untouched by packaging. It's a good location for providing default, commented-out example configurations as long as they're marked `config,noreplace`

### PR DESCRIPTION
**Pull request by brianhlin**
Fixes #1660

This changes the default configuration of the Pelican and OSDF services, clearing up ownership 

1.  The Pelican project owns each service config entrypoint, e.g. `/etc/pelican/pelican-origin.yaml`
1.  Federation admins can dump and own files in `/usr/share/pelican/config.d`. I don't actually expect this to see a ton
    of use but since we own (1), making this a directory will allow federation admins to package federation-specific
    config without needing our intervention
1.  Service admins own files in `/etc/pelican/config.d`

(1) and (3) are particularly important as they allow us to more effectively change defaults, including alignment of
`pelican` and `osdf` binaries at the server level and potentially consolidating down to a single `pelican.yaml`
entrypoint.

N.B. this does somewhat break the current paradigm where users could feasibly run multiple different services on a
single host. I think it's fine to do this because:

1.  This was never supported in the proto-Pelican days. It's not clear to me that anyone actually wants it
1.  If someone really wants to do this, they can use their own custom config files + systemd overrides
1.  If we really wanted to, we could add another dir layer per service type (e.g., `/etc/pelican/config.d/origin`) in
    the future

I did not add an example file for caches since it's not clear exactly what we should be telling users (see #1664).

Note to self the OSG Software Team needs to modify the `osdf-server` RPMs to pull in the following files:

-   `systemd/10-osdf-defaults.yaml`
-   `systemd/examples/15-osdf.yaml`
-   `systemd/examples/50-webui.yaml` (though I'm not sure we should be disabling this by default?)

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I only skimmed the description so far, but this caught my eye:

> (though I'm not sure we should be disabling [the Web UI] by default?)

I think enabling it by default is a security hazard until #1227 is implemented.

**Review by matyasselmeci — APPROVED** [review]
LGTM. Is there a Jira ticket for updating the osdf-server RPMs?

**Comment by bbockelm** [comment]
@brianhlin - there's a fix for various race conditions in the Mac OS X testing in main.  Can you merge or rebase so we get a clean bill of health?

**Comment by brianhlin** [comment]
Done

@matyasselmeci https://opensciencegrid.atlassian.net/issues/SOFTWARE-6028

**Pull request merged**
